# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sg_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usr_system',
            name='id',
        ),
        migrations.AlterField(
            model_name='usr_system',
            name='dni',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
