# Generated by Django 2.0 on 2018-08-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sg_usuario', '0002_auto_20171118_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usr_system',
            old_name='dni',
            new_name='id',
        ),
    ]
